### PR TITLE
update dependencies to non-vulnerable versions

### LINKED ISSUE #99: NPM flags many vulnerabilities
Wondering if this project is still maintained?  Upon install I see 12 vulnerabilities (5 moderate, 7 high)

Thanks!

### PR DESCRIPTION
**Pull request by toufali**
Fixes #99 

- reduces vulnerabilities from 16 (6 moderate, 7 high, 3 critical) to 0
- Tests are still passing, but need to confirm all is working as expected with real-world test.
- Most noticeable change may be removal of `offline-github-changelog`, which caused many vulns.  Changelogs can be auto-generated via GitHub tags/releases section – perhaps `offline-github-changelog` will not be missed?
- `semver-regex` and `got` were updated via manual `package-lock.json` update (which is frowned upon).  Both are deps of pngquant-bin which doesn't appear to have (or will) resolve the vulns.
- package-lock generation was disabled 4 years ago.  In order to resolve vulnerabilities, this was re-enabled.

### CODE REVIEW

**Comment by papandreou** [comment]
I'd rather not let go of `offline-github-changelog` -- could we fix those problems over at https://github.com/sunesimonsen/offline-github-changelog instead? I'm a co-maintainer, so can help get fixes landed quickly.

Also, I don't want to introduce a package lock file here. It's ignored when `pngquant` is installed as a dependency anyway, so I doubt that it actually gets rid of the security vulnerabilities in that context.

**Comment by papandreou** [comment]
I merged that and updated a bunch of other stuff, released `offline-github-changelog@3.0.0`, then updated to that on master. Also updated `pngquant-bin` to the latest version. How does it look now?

**Comment by toufali** [comment]
With your update to `offline-github-changelog` I now see 15 vuln instead of 16 upon install.  Unfortunately the package `@transformation/ejs` (used by `offline-github-changelog@3.0.0`) is still tied to a critical version of `ejs` ( <3.1.7 ) https://github.com/sunesimonsen/transformation/blob/40d752aee34b08ce69296fc8c54d015614df8d2e/packages/ejs/package.json#L22

We could further reduce vulnerabilities down to 12 by upgrading Mocha to `10.1.0` or higher: https://github.com/papandreou/node-pngquant/pull/101

That should only leave `pngquant-bin` and `offline-github-changelog` with ~12vulnerabilities (3 of which are critical).

**Comment by papandreou** [comment]
@toufali, `@transformation/ejs` version 6.0.1 got released with the `ejs` dependency bumped.

**Comment by papandreou** [comment]
Haha, that's also a fine outcome. If I was to build an image processing pipeline with node.js today, I'd probably reach for WASM-based builds of these tools.

**Pull request closed without merging**
